idf_component_register(
    SRCS 
        "main.c"
        "hal/dac80508.c"
        "hal/dac_timer.c"
        "core/frame_buffer.c"
        "core/dac_engine.c"
        "input/etherdream_server.c"
        "web/http_server.c"
        "web/ota_handler.c"
    INCLUDE_DIRS 
        "."
    REQUIRES
        driver
        esp_wifi
        esp_netif
        esp_http_server
        nvs_flash
        json
        fatfs
        sdmmc
        app_update
)
